// Generated by CoffeeScript 1.7.1
(function() {
  var makeCode, offCode, onCode, onCodes;

  onCodes = ['var index = 0', 'g._bot_ = true', 'function _botFunc_() {', '  g.keys[37] = g.keys[38] = g.keys[39] = g.keys[40] = false', '  if (g._bot_ == false) return', '  g.keys[37 + (index++ % 4)] = true', '  setTimeout(_botFunc_, 500)', '}', '_botFunc_()'];

  onCode = onCodes.join(';');

  offCode = "g._bot_ = false;";

  makeCode = function(innerCode) {
    return "var script = document.createElement(\"script\");\nscript.appendChild(document.createTextNode(\"" + innerCode + "\"));\ndocument.body.appendChild(script);\ndocument.body.removeChild(script);";
  };

  if (!chrome.extension.getBackgroundPage().isWandering) {
    chrome.extension.getBackgroundPage().isWandering = true;
    chrome.tabs.query({
      active: true
    }, function(tabs) {
      return chrome.tabs.executeScript({
        code: makeCode(onCode)
      }, function(ret) {
        return document.body.appendChild(document.createTextNode('Started'));
      });
    });
  } else {
    chrome.extension.getBackgroundPage().isWandering = false;
    chrome.tabs.query({
      active: true
    }, function(tabs) {
      return chrome.tabs.executeScript({
        code: makeCode(offCode)
      }, function(ret) {
        return document.body.appendChild(document.createTextNode('Stopped'));
      });
    });
  }

}).call(this);

//# sourceMappingURL=popup.map
