// Generated by CoffeeScript 1.7.1
(function() {
  exports.index = function(req, res) {
    return res.render('index', {
      title: 'GCM Demo'
    });
  };

}).call(this);

//# sourceMappingURL=index.map
